---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-8.7

suites:
  - name: default
    run_list:
      - recipe[basebuild::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
