---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-8.7

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    # encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[basebuild::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
